language: ruby
rvm:
 - 2.2.5

addons:
 packages:
  - unzip
  - google-chrome-stable
before_install:
  # Install Chrome driver
 - wget http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip
 - unzip chromedriver_linux64.zip
 - sudo chmod u+x chromedriver
 - sudo mv chromedriver /usr/bin/

 # For selenium in headless linux system, But no need when PhantomJS
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start

services:
  - postgresql

before_script:
  - psql -c 'create database shortcutsworld_test;' -U postgres
  - cp config/database.yml.travis config/database.yml