sudo: required
language: ruby
rvm:
 - 2.2
before_install:
 - wget http://chromedriver.storage.googleapis.com/2.8/chromedriver_linux32.zip
 - unzip chromedriver_linux32.zip
 - mv chromedriver /usr/bin/
 - chmod u+x /usr/bin/chromedriver
 - ls /usr/bin/