language: ruby
rvm:
 - 2.2
before_install:
 - wget http://chromedriver.storage.googleapis.com/2.19/chromedriver_linux64.zip
 - unzip chromedriver_linux64.zip
 - sudo chmod u+x chromedriver
 - sudo mv chromedriver /usr/bin/
 -