language: ruby
rvm:
 - 2.2.5

node_js:
  - "iojs"

addons:
 packages:
  - unzip
  - google-chrome-stable
before_install:
  # Install Chrome driver
 - wget http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip
 - unzip chromedriver_linux64.zip
 - sudo chmod u+x chromedriver
 - sudo mv chromedriver /usr/bin/



services:
  - postgresql

before_script:
  - psql -c 'create database shortcutsworld_test;' -U postgres
  - cp config/database.yml.travis config/database.yml