default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: shortcutsworld_development
  username: christian

test:
  <<: *default
  database: shortcutsworld_test
  username: christian
